version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data/house_prices.csv:/house_prices.csv
    environment:
      - POSTGRES_USER=Evgenii
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=postgre_db
    ports:
      - "5432:5432"
    networks:
      - spark-network

  spark-master:
    image: bitnami/spark:latest
    ports:
      - "8082:8082"
      - "7077:7077"
      - "4042:4042"
    environment:
      - SPARK_MODE = master
    volumes:
      - ./my_spark.py:/opt/bitnami/spark/my_spark.py
      - ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
    networks:
      - spark-network
  spark-worker-1:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
    networks:
      - spark-network
  spark-worker-2:
      image: bitnami/spark:latest
      environment:
        - SPARK_MODE=worker
        - SPARK_MASTER_URL=spark://spark-master:7077
      volumes:
        -  ./postgresql-jdbc.jar:/opt/bitnami/spark/jars/postgresql-jdbc.jar
      networks:
        - spark-network
networks:
  spark-network:
    driver: bridge


